### ISSUE TITLE
Client-1.14.4 to Server-1.16.5 with viaFabric.    Bad packet id 16

### ISSUE THREAD

**Issue by FrankHan052176** [ViaVersion/ViaFabric#155]
**Describe the bug, provide any errors**
client(1.14.4 vanila) can't connect to server(1.16.5 with viaFabric)

**How can we reproduce it?**
try to use client(1.14.4) to login in the server(1.16.5 with viafabric)

**Expected behaviour**
i hope that i can login in my server

**Screenshots**
no screenshots,but i have the log: https://gist.github.com/FrankHan052176/52754b70963492683f4fce4e004082c5

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
client(1.16.5) whatever it is fabric or forge or vanila can join my server.

**Additional server info**
- Is server using a proxy (eg. BungeeCord/Velocity)?
- no
 What software is it using and what plugins? (Debug HUD may have it (F3))
i can't login in my server
 Are you running on client-side mode?
no,it's server-side mode

**Comment by FrankHan052176** [comment]
when client is logining in the server, it's just like this
![image](https://user-images.githubusercontent.com/48244729/131239996-6a2d9cc1-4072-4393-afd2-06925f9b959a.png)

**Comment by Kichura** [comment]
Closing this issue due to the following things:

1. There is no viaversion dump of this meaning we can't figure out what's clearly wrong,
2. This is likely to be a third-party plugin/mod on the server itself that may be causing viafabric to fail,
3. Should this issue continue to happen, Please send a response whenever needed.
