### ISSUE TITLE
Placeholder returns 1.16.3 on 1.8.x

### ISSUE THREAD

**Issue by Permanently** [ViaVersion/ViaFabric#60]
**Describe the bug, provide any errors**
When using the `%viaversion_player_protocol_version%` on PlaceholderAPI (currently on 2.10.8), it returns 1.16.3. However, I'm running on 1.8.9.

- [ ] It seems to not happen when using ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity server.

**How can we reproduce it?**
1. Login on 1.8.x, onto a 1.12.2 server with PlaceholderAPI, ViaVersion, ViaBackwards and ViaRewind installed.
2. Type `/papi parse me %viaversion_player_protocol_version%`.
3. Observe.

**Expected behaviour**
Well... I was expecting it to show my version.

**Screenshots**
[Here.](https://overconscio.us/HJWbf2.png)

**ViaVersion Dump:**
[Here.](https://dump.viaversion.com/3878ec55cb432fb2d3781b740e1bf6d0a08c701ba6abd4f1e6ca21c2b501d417)

**Additional server info**
ViaVersion (3.2.0-SNAPSHOT), ViaBackwards (3.2.0-SNAPSHOT) and ViaRewind (1.5.2-SNAPSHOT) are all installed Paper-side. They're all behind a Travertine proxy.

**Comment by Xernium** [comment]
I am pretty sure you're running an unsupported setup:   
If you attempt to run the Via plugins on both your proxy (velocity or bungee) **and** all your backend servers you will get weird behavior.    
Reason: The proxy will try to translate your version to the backend server version. But since the backend server doesn't send a clear version it will translate to one of a few options. Your backend server will then translate again to its native version.   
This is how false versions get passed around.    
If you need to use the API on a backend you **cannot** have the Via plugins installed on the proxy.    
(There is an edge-case workaround for if you need to use Via on both the proxy and end servers but we don't provide support for that as much as only giving advice)

**Comment by Permanently** [comment]
I'm not running Via* plugins on proxy. As said:

> ViaVersion (3.2.0-SNAPSHOT), ViaBackwards (3.2.0-SNAPSHOT) and ViaRewind (1.5.2-SNAPSHOT) are all installed Paper-side.

**Comment by Permanently** [comment]
ViaVersion was on my proxy server for whatever reason. My bad.
