### ISSUE TITLE
version for forge 1.12.2

### ISSUE THREAD

**Issue by darkx239** [ViaVersion/ViaFabric#72]
**Is your feature request related to a problem? Please describe.**

**Is this related specifically to ViaFabric?**
(Optional)
- [ ] It seems to not apply for ViaVersion/ViaBackwards/ViaRewind installed on Bukkit/BungeeCord/Sponge/Velocity servers.

**Describe the solution you'd like**
A version for 1.12.2 forge

**Describe alternatives you've considered**
none

**Which versions is this for?**
1.12.x

**Comment by Username404-59** [comment]
You want to connect to an older version than yours, or a newer one?
If you want to connect to an older version (ex: 1.9), you can already use https://github.com/5zig/The-5zig-Mod/releases/tag/3.12.5 and add https://github.com/Gerrygames/ClientViaVersion/releases/tag/v2.0.8 in the plugins folder of 5zig.

**Comment by Xernium** [comment]
I was about to say; that mod is the only thing available in this regard currently. Making Via support forge without modifying forge behavior is next to impossible and thus not planned or a sought-after endeavor. Especially given that any kind of mod that modifies the vanilla game in any sort of meaningful way is gonna break Via support.
Since Via* is all open source though, you may create that kind of mod yourself if you so desire.

**Comment by creeper123123321** [comment]
See https://www.curseforge.com/minecraft/mc-mods/viaforge
