### ISSUE TITLE
Port to more Legacy Fabric versions

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#85]
- [ ] 1.7.10
- [ ] 1.12.2
- [ ] 1.13.2
- more if people request?

**Comment by Kichura** [comment]
Could be done since a small portion of servers have started to relay on that version - Unsure how this would turn out though.

**Comment by Kichura** [comment]
1. Since ViaFabric does not support 1.7.x clients of any kind; 1.7.10 is essentially not possible without writing support for it before hand,
2. 1.13.2 may be possible but this one comes with it's set of problems which is broken connectivity for example,
3. 1.12.2 can definitely be tried - only problem is that we need a specific version of mod menu to work with.

**Comment by HowardZHY** [comment]
> 1. Since ViaFabric does not support 1.7.x clients of any kind; 1.7.10 is essentially not possible without writing support for it before hand,
> 2. 1.13.2 may be possible but this one comes with it's own set of problems which is broken connectivity for example,
> 3. 1.12.2 can definitely be tried - only problem is that we need a specific version of mod menu to work with.

https://github.com/ThinkingStudios/ModMenuLegacy This ModMenu fork working on 1.12.2

**Comment by Kichura** [comment]
1.12.2 support is now available in dev.
